config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  devise_for :students, :lecturers, skip: :sessions

  resources :lectures, only: [:index, :new, :create]

  root 'home#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  mount_uploader :video, VideoUploader

  belongs_to :lecturer
  belongs_to :course

  validates_presence_of :name
  validates_uniqueness_of :name, scope: :lecturer_id
  validates_presence_of :video
  validates_presence_of :course_id

  validate :valid_course

  private
    def valid_course  
      self.errors.add(:course_id, "^ Course is invalid.") unless Course.exists? course_id
    end
end

app/models/lecturer.rb
class Lecturer < User
  has_many :lectures
end

app/models/student.rb
class Student < User
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  self.inheritance_column = :access_type
  
  def is_student?
    self.access_type == "Student"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_devise_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def not_authorized
    redirect_to root_path, alert: "You are not authorized to access that functionality."
  end

  %w(Lecturer Student).each do |k| 
    define_method "current_#{k.underscore}" do 
      current_user if current_user.is_a?(k.constantize)
    end 

    define_method "authenticate_#{k.underscore}!" do 
      |opts={}| send("current_#{k.underscore}") || not_authorized 
    end 
  end

  protected

  def configure_devise_permitted_parameters
    registration_params = [:first_name, :last_name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
    }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_lecturer!
  before_action :set_course, only: [:edit, :update, :destroy]

  def index
    @courses = current_lecturer.courses
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = current_user.courses.new course_params

    if @course.save
      redirect_to courses_path, notice: 'Course was successfully created.'
    else
      render :new
    end
  end

  def update
    if @course.update course_params
      redirect_to courses_path, notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    
    redirect_to courses_url, notice: 'Course was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = current_lecturer.courses.find params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :authenticate_lecturer!

  def index
    @lectures = current_lecturer.lectures
  end

  def new
    @lecture = Lecture.new
  end

  def create
    @lecture = current_lecturer.lectures.new lecture_params
    if @lecture.save
      redirect_to lectures_path, notice: "Lecture created successfully."
    else
      render :new
    end
  end

  private
    def lecture_params
      params.require(:lecture).permit(:course_id, :name, :video)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.haml
= form_for(@course, html: { class: "form-horizontal"}) do |f|
  - if @course.errors.any?
    #error_explanation
      %h2
        = pluralize(@course.errors.count, "error")
        prohibited this course from being saved:
      %ul
        - @course.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-5
      = f.text_field :name, autofocus: true, class: "form-control", placeholder: "Course Name"
  .form-group
    .col-sm-offset-2.col-sm-5
      = f.submit "Create Course", class: "btn btn-primary"

app/views/courses/edit.html.haml
%h1 Editing course
= render 'form'
= link_to 'Show', @course
|
\#{link_to 'Back', courses_path}

app/views/courses/index.html.haml
%legend Listing courses
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @courses.each do |course|
      %tr
        %td= course.name
        %td= link_to 'Edit', edit_course_path(course)
        %td= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }
%br
  = link_to 'New Course', new_course_path

app/views/courses/new.html.haml
%h1 New course
= render 'form'
= link_to 'Back', courses_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MyLecture
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag :defaults
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-primary{:role => "navigation"}
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %a.navbar-brand{:href => root_path} My Lecture
        / Collect the nav links, forms, and other content for toggling
        /
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  = current_user.email
                  %span.caret
                %ul.dropdown-menu{:role => "menu"}
                  %li
                    - if current_user.is_student?
                      = link_to "Edit Profile", edit_student_registration_path(current_user.id)
                    - else
                      = link_to "Edit Profile", edit_lecturer_registration_path(current_user.id)
                  %li.divider
                  %li
                    = link_to "Logout", destroy_user_session_path, method: :delete
            - else
              %li
                %a{:href => new_user_session_path} Sign In
              %li
                %a{:href => new_student_registration_path} Student Sign Up
              %li
                %a{:href => new_lecturer_registration_path} Lecturer Sign Up
              
            /
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Dropdown
                  %span.caret
                %ul.dropdown-menu{:role => "menu"}
                  %li
                    %a{:href => "#"} Action
                  %li
                    %a{:href => "#"} Another action
                  %li
                    %a{:href => "#"} Something else here
                  %li.divider
                  %li
                    %a{:href => "#"} Separated link
          %form.navbar-form.navbar-right{:role => "search"}
            .form-group
              %input.form-control{:placeholder => "Search", :type => "text"}
            %button.btn.btn-default{:type => "submit"} Submit

    - if user_signed_in?
      .col-sm-3
        .navbar-default.sidebar{:role => "navigation"}
          .sidebar-nav.navbar-collapse
            %ul#side-menu.nav
              %li
                = link_to lectures_path, class: "active" do
                  %i.fa.fa-dashboard.fa-fw
                  Show all Lectures
          / /.sidebar-collapse
      .col-sm-9
        = yield
    - else
      = yield

app/views/lectures/index.html.haml
= link_to "New Lecture", new_lecture_path

%legend Lectures
%ul
  - @lectures.each do |lecture|
    %li
      %b.course= lecture.course.name
      .name= lecture.name
      .lecture
        = video_tag lecture.video.url(:mp4), size: "240x180", :controls => true

app/views/lectures/new.html.haml
= form_for @lecture do |f|
  .field
    = f.label :course_id, "Course"
    = f.select :course_id, Course.all.map{|e| [e.name, e.id]}

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :video
    = f.file_field :video, id: "fileupload"

  .field
    = f.submit

app/views/users/shared/_links.haml
- if controller_name != 'sessions'
  = debugger
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/